[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
    'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc',
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"